Add guarded batch functions in Gateway contract
etherspot/etherspot-contracts pull request #112
Opened 2022-10-10 16:29 UTC by marie-fourier

## Description

- added guarded batch functions in `src/gateway/Gateway.sol`
`function sendBatchGuarded`
`function sendBatchFromAccountGuarded`
`function delegateBatchGuarded`
`function delegateBatchWithGasPriceGuarded`
`function delegateBatchesGuarded`

- updated tests for Gateway `(100% Statements 43/43, 80.95% Branches 34/42, 100% Functions 19/19, 100% Lines 49/49)`

## Motivation and Context

-

## How Has This Been Tested?

- unit tests
-
-

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-10-10 16:32 UTC, zincoshine requested changes
It is better to implement this change in a new contract, which will make it easier to switch between the two if and when needed.

2022-10-10 16:32 UTC, zincoshine commented on src/gateway/Gateway.sol
> +contract Gateway is Initializable, SignatureValidator, Guarded {
Create a new version of Gateway called GatewayV2

2022-10-10 16:33 UTC, marie-fourier commented on src/gateway/Gateway.sol
> +contract Gateway is Initializable, SignatureValidator, Guarded {
agree. will do this

2022-10-12 11:37 UTC, marie-fourier commented
@zincoshine HopFacet.ts changed because I removed a typo from there (updated in the pr description)

2022-10-12 11:40 UTC, zincoshine commented
Pls deploy on gnosis testnet, avax testnets as well

2022-10-12 12:00 UTC, zincoshine approved these changes

2022-10-12 12:38 UTC, lbw33 approved these changes

2022-10-12 12:45 UTC, merged