Deployed OKX or OKTC Testnet
etherspot/etherspot-contracts pull request #132
Opened 2023-04-21 13:46 UTC by kaushalrajbacancy

- Added OKTC and deployed the contract for testnet.

## Description

- OKX is renamed to OKTC on their website. So, we have followed the same naming convention instead of using ChainList.

## Motivation and Context

- https://www.okx.com/en-in/oktc/docs/dev/api/oktc-api/json-rpc-api#testnet-(chain-id:-0x41,-65-in-decimal)
- https://www.okx.com/en-in/oktc/docs/dev/quick-start/overview.html

## How Has This Been Tested?

- This has not been tested yet as backend changes are pending to be done.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2023-04-24 15:56 UTC, vignesha22 approved these changes
LGTM

2023-05-08 14:15 UTC, ch4r10t33r requested changes
deployments for Klaytn are missing? @vignesha22 @kaushalrajbacancy

2023-05-08 14:19 UTC, ch4r10t33r reviewed
Ok, I notice these files are already present. Approved.

2023-05-08 14:20 UTC, ch4r10t33r approved these changes

2023-05-09 04:23 UTC, merged