Feature/pro 212 superfluid balance helpers
etherspot/etherspot-contracts pull request #64
Opened 2022-06-08 14:43 UTC by lukewickens1989

- Added BalancesHelperV2 contract to get account balances for Superfluid tokens (pure and wrapped/native).
- Added test suite to check contract.
- Added 0.8.4 solidity compiler to hardhat.config.
- Updated solhint package to account for later Solidity code used in contract.

2022-06-09 08:54 UTC, zincoshine requested changes
Where is the deployment script for the new contract? Please have that ready and then test it locally or on Etherspot network.

2022-06-09 09:56 UTC, lukewickens1989 commented on package.json
> +    "web3": "^1.7.3"
This is a dev dependency of the [hardhat-web3 package](https://hardhat.org/plugins/nomiclabs-hardhat-web3). The reason this was used is that this is the method that Superfluid use in order to set up their tests ([Superfluid example code](https://github.com/superfluid-finance/protocol-monorepo/tree/dev/examples)), which I mainly used as a guide.

2022-06-09 14:00 UTC, lukewickens1989 commented on package.json
> +    "@nomiclabs/hardhat-web3": "^2.0.0",
Done

2022-06-10 11:33 UTC, zincoshine commented on package.json
> +    "web3": "^1.7.3"
Pls can we then change it to a specific web3 package? say 1.7.3 ?

2022-06-10 11:33 UTC, zincoshine commented on package.json
> +    "web3": "^1.7.3"
@lukewickens1989

2022-06-10 11:51 UTC, lukewickens1989 commented on package.json
> +    "web3": "^1.7.3"
I think I locked the version in the last commit where I added the deployment script

2022-06-10 12:13 UTC, zincoshine approved these changes
LGTM

2022-06-10 12:16 UTC, merged