integration of connext amarok
etherspot/etherspot-contracts pull request #74
Opened 2022-06-29 13:04 UTC by marie-fourier

Updated hardhat to 2.9.8, because forking was not working in the version (Ref: https://github.com/NomicFoundation/hardhat/releases/tag/2.9.2)

Changed diamond contracts solidity version to dynamic ">=0.8.4 <0.9.0". LibDiamond.sol is be used by many facets that may have different versions of solidity because they depend on external packages. For example, AmarokFacet makes heavy use of nxtp/contracts package which is written in 0.8.11. Other bridges will use another package written in different solidity version

2022-06-29 18:03 UTC, zincoshine commented
@marie-fourier is this ready for review?

2022-06-29 18:19 UTC, zincoshine requested changes
Does Connext contract provide the list of tokens supported by them on a given chain for bridging?

2022-06-29 18:19 UTC, zincoshine commented on package.json
> +    "@connext/nxtp-contracts": "^0.2.0-beta.10",
Can we pls use an exact version of an external package?

2022-06-29 18:19 UTC, zincoshine commented on package.json
> +    "@openzeppelin/contracts-upgradeable": "^4.6.0",
Same as above an exact version. These external packages are not backward compatible and if a new version is released our build will break.

2022-06-29 18:19 UTC, zincoshine commented on src/bridges/facets/AmarokFacet.sol
> +  bytes32 internal constant NAMESPACE = hex"a4cabcf91d6212ba2873e2f19de6e26ae65fd3280b9eaa6d8bc38c5fba52ec9d"; //keccak256("io.etherspot.facets.amarok");
Is this keccak256("io.etherspot.facets.amarok");

2022-06-29 18:19 UTC, zincoshine commented on src/bridges/facets/AmarokFacet.sol
> +  bytes32 internal constant NAMESPACE = hex"a4cabcf91d6212ba2873e2f19de6e26ae65fd3280b9eaa6d8bc38c5fba52ec9d"; //keccak256("io.etherspot.facets.amarok");
Can't we use etherspot-specific namespace?

2022-06-29 18:19 UTC, zincoshine commented on src/bridges/facets/AmarokFacet.sol
> +    uint32 chainId;
From solidity 0.8.0 we can get the current chainId using `block.chainid`. Do we then need this variable in storage?

2022-06-29 18:19 UTC, zincoshine commented on src/bridges/facets/AmarokFacet.sol
> +contract AmarokFacet {
Amarok is just a version name of the Connext product. I suggest we rename the contract to ConnextFacet or NxtpFacet

2022-06-29 18:19 UTC, zincoshine commented on src/bridges/facets/AmarokFacet.sol
> +  event AmarokInitialized(address _connext);
Pls see above on the contract name and change events and function names accordingly.

2022-06-29 18:20 UTC, zincoshine commented
Can't you get tests working on Etherspot chain? We can configure Etherspot chain with the necessary changes if required.

2022-06-29 19:36 UTC, lukewickens1989 commented on src/bridges/facets/AmarokFacet.sol
> +  bytes32 internal constant NAMESPACE = hex"a4cabcf91d6212ba2873e2f19de6e26ae65fd3280b9eaa6d8bc38c5fba52ec9d"; //keccak256("io.etherspot.facets.amarok");
Do we need this? As there is no diamond storage being used can we just store this as variables inside the contract?

2022-06-29 19:37 UTC, lukewickens1989 commented on src/bridges/facets/AmarokFacet.sol
> +    uint32 chainId;
Agreed.

2022-06-29 21:32 UTC, zincoshine commented on src/bridges/facets/AmarokFacet.sol
> +  bytes32 internal constant NAMESPACE = hex"a4cabcf91d6212ba2873e2f19de6e26ae65fd3280b9eaa6d8bc38c5fba52ec9d"; //keccak256("io.etherspot.facets.amarok");
I thought the hex was used to pull up a specific version of the contract code from storage?

2022-06-30 05:53 UTC, marie-fourier commented on src/bridges/facets/AmarokFacet.sol
> +    uint32 chainId;
yes, it actually should be named `domainId` and it is different from chain id

2022-06-30 05:54 UTC, marie-fourier commented on src/bridges/facets/AmarokFacet.sol
> +  bytes32 internal constant NAMESPACE = hex"a4cabcf91d6212ba2873e2f19de6e26ae65fd3280b9eaa6d8bc38c5fba52ec9d"; //keccak256("io.etherspot.facets.amarok");
>Is this keccak256("io.etherspot.facets.amarok");

yes

2022-06-30 05:56 UTC, marie-fourier commented
> Can't you get tests working on Etherspot chain? We can configure Etherspot chain with the necessary changes if required.

@zincoshine Integration contracts must interact with connext's contracts in goerli chain. If we can hardfork goerli in our etherspot chain, then we can use it

2022-06-30 06:00 UTC, marie-fourier commented on package.json
> +    "@openzeppelin/contracts-upgradeable": "^4.6.0",
fixed

2022-06-30 08:37 UTC, lukewickens1989 commented on src/bridges/facets/AmarokFacet.sol
> +  bytes32 internal constant NAMESPACE = hex"a4cabcf91d6212ba2873e2f19de6e26ae65fd3280b9eaa6d8bc38c5fba52ec9d"; //keccak256("io.etherspot.facets.amarok");
Sorry yes you are right

2022-06-30 10:21 UTC, zincoshine commented
deploy/203_deploy_amarok_facet.ts should be renamed to deploy/203_deploy_connext_facet.ts

2022-06-30 10:23 UTC, zincoshine requested changes

2022-06-30 10:23 UTC, zincoshine commented on extensions/constants.ts
> +    defaultProviderUrl: 'https://goerli.infura.io/v3/000a856f3b024bcba2f5c507fe62738d',
Do not store Infura keys in the repo. Always use environment variables for these things.

2022-06-30 10:46 UTC, marie-fourier commented on extensions/constants.ts
> +    defaultProviderUrl: 'https://goerli.infura.io/v3/000a856f3b024bcba2f5c507fe62738d',
removed

2022-06-30 17:23 UTC, zincoshine requested changes
@marie-fourier `src/bridges/facets/AmarokFacet.sol` file name has to changed to `ConnextFacet.sol`

2022-06-30 17:23 UTC, zincoshine commented
Please check all such references to Amarok and change it to Connext

2022-07-11 12:27 UTC, lukewickens1989 approved these changes

2022-07-11 13:32 UTC, riccardopillar approved these changes

2022-07-12 02:01 UTC, merged